# Generated by Django 3.1.1 on 2020-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200930_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
