# Generated by Django 3.1.1 on 2020-09-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200930_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number_id',
            new_name='product_id',
        ),
    ]
